// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FWF.Dal.Models;

[Table("route_staging")]
public partial class RouteStaging
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("airline")]
    [StringLength(50)]
    public string Airline { get; set; }

    [Column("sourceAirport")]
    [StringLength(50)]
    public string SourceAirport { get; set; }

    [Column("destinationAirport")]
    [StringLength(50)]
    public string DestinationAirport { get; set; }

    [Column("codeShare")]
    [StringLength(50)]
    public string CodeShare { get; set; }

    [Column("stops")]
    public int? Stops { get; set; }

    [Column("equipment")]
    [StringLength(50)]
    public string Equipment { get; set; }

    [Column("pipelineRunId")]
    public Guid? PipelineRunId { get; set; }

    [Column("provider")]
    [StringLength(50)]
    public string Provider { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }
}