# This is a basic workflow to help you get started with Actions

name: fwf-infrastructure

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}    # set this to your Azure Subscription Id
    AZURE_RESOURCEGROUP_NAME: fwf-rg                      # set this to your preferred resource group name
    SQLSERVER_NAME: fwf-db-srv                          # set this to your preferred sql server name
    DATABASE_NAME: fwfdb                   # set this to your preferred sql database name
    SQLADMIN_LOGIN: ${{ secrets.SQLADMIN_LOGIN  }}                # Create a secret in your Github repo for the SQL Admin login name you want to use
    SQLADMIN_PASS: ${{ secrets.SQLADMIN_PASS  }}                 # Create a secret in your Github repo for the SQL Admin password you want to use
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    fwf-create-azure-resources:
      runs-on: ubuntu-latest
      steps:
      
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FWF_ENV_SPN }}
      
      # Deployment of template    
      - name: Deploy ARM Template (resourcegroup - ${{ env.AZURE_RESOURCEGROUP_NAME }})
        uses: azure/arm-deploy@v1
        with:
          # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: centralus # Set this to your target region
          template: repo/FWF/deployment/Azure Templates/fwf-resource-group.json  # Set this to the location of your template file
          parameters: repo/FWF/deployment/Azure Templates/fwf-resource-group.parameters.json rgName=${{env.AZURE_RESOURCEGROUP_NAME}} #override rgName in parameters file


      # Deployment of template    
      - name: Deploy ARM Template cems-database ${{ env.SQLSERVER_NAME }}
        uses: azure/arm-deploy@v1
        with:
          # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{env.AZURE_RESOURCEGROUP_NAME}}
          region: centralus # Set this to your target region
          template: repo/FWF/deployment/Azure Templates/fwf-database.json  # Set this to the location of your template file
          parameters: repo/FWF/deployment/Azure Templates/fwf-database.parameters.json sqlServerName=${{env.SQLSERVER_NAME}} databaseName=${{env.DATABASE_NAME}} sqlAdminLogin=${{env.SQLADMIN_LOGIN}} sqlAdminPass=${{env.SQLADMIN_PASS}} # Set this to the location of your parameters file
