# This is a basic workflow to help you get started with Actions

name: fwf-infrastructure

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    fwf-create-azure-resources:
      runs-on: ubuntu-latest
      steps:
      
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.fwf_env_SPN }}
